### ISSUE TITLE
Button stays pressed

### ISSUE THREAD

**Issue by lkdgroot** [leerob/Space_Invaders#9]
Just a small bug.
Has any one had a bug where your ship keeps going left/right even if you don't keep pushing the button? It goes away for me if you repush the direction you go in, but if there is some kind of fix, or if any one knows where the bug comes from that would be great.

Using the code for my thesis, so  need to cover a couple of things in it.

**Comment by leerob** [comment]
Hmm, I haven't seen this one. If you manage to hit it again and can consistently reproduce it, would you mind adding those comments here?

I'd love to see your thesis when you're finished! 👍

**Comment by lkdgroot** [comment]
Apparently it 's a performance issue on my laptop. I've seen several systems and haven't been able to reproduce it on those. Still a weird issue though.

Thesis is at least moving along. All though I've probably made a monster out of your code XD

**Comment by leerob** [comment]
I'm gonna go ahead a close this then 👍Good luck with the rest of it!
